# hello me



_i am starting numpy for opencv_

* soo lets go *

In [2]:
import numpy as np

In [3]:
firstarry = np.array([1,24,35,46,38,96])

now the above array is 1 D array cause single bracket[]

In [4]:
firstarry

array([ 1, 24, 35, 46, 38, 96])

In [5]:
firstarry[2]

np.int64(35)

In [6]:
firstarry.shape

(6,)

In [7]:
secondarry= np.array([[1,23,63,73,235,634,46]])

this is a 2D array as this array have 2 brackets

In [8]:
secondarry[0,4]

np.int64(235)

In [9]:
secondarry.shape

(1, 7)

We can also chose the data type for our interger in array otherwise int64 is by default

In [10]:
firstarry = np.array([1,24,35,46,38,96],np.int8)

In [11]:
secondarry= np.array([[1,23,63,73,235,634,46]],np.int32)

In [12]:
firstarry


array([ 1, 24, 35, 46, 38, 96], dtype=int8)

In [13]:
secondarry

array([[  1,  23,  63,  73, 235, 634,  46]], dtype=int32)

We can aslo change the integer 

In [14]:
secondarry[0,2]

np.int32(63)

In [15]:
secondarry[0,2]=75

In [16]:
secondarry

array([[  1,  23,  75,  73, 235, 634,  46]], dtype=int32)

# Changed

# Array creation: Conversion from other Python structures

In [17]:
listarray=np.array([[1,2,3],[12,34,54],[75,45,34]])

In [18]:
listarray



array([[ 1,  2,  3],
       [12, 34, 54],
       [75, 45, 34]])

In [19]:
listarray[1,2]

np.int64(54)

In [20]:
listarray[1,2]=90

In [21]:
listarray

array([[ 1,  2,  3],
       [12, 34, 90],
       [75, 45, 34]])

In [22]:
listarray.size

9

In [23]:
listarray.shape

(3, 3)

In [24]:
listarray.dtype

dtype('int64')

In [25]:
dict=np.array({1,32,34,64})

In [26]:
dict

array({32, 1, 34, 64}, dtype=object)

In [28]:
zeros=np.zeros([2,5])

In [29]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
rng=np.arange(88)

In [31]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [32]:
lsp=np.linspace(1,60,10)

In [33]:
lsp

array([ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222,
       33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ])

In [34]:
emp=np.empty([2,6])

In [35]:
emp

array([[1.07671537e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 1.21190256e-305, 5.64233733e-067],
       [5.59011067e-091, 7.92560423e+165, 9.99643342e-048,
        5.26437365e-037, 3.99910963e+252, 4.93432906e+257]])

In [36]:
emp[1,1]=30

In [37]:
emp

array([[1.07671537e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 1.21190256e-305, 5.64233733e-067],
       [5.59011067e-091, 3.00000000e+001, 9.99643342e-048,
        5.26437365e-037, 3.99910963e+252, 4.93432906e+257]])

In [38]:
emp_lk=np.empty_like(rng)

In [39]:
emp_lk

array([                  0,     140708236243136,                 664,
                        -1,  527773634396160100, 8031151179464336711,
       2902988274244535666, 8245935277853325887, 4551015458302619004,
       6304039401398879546, 8946795858661110369, 7222154395322564392,
       8386111997913016421, 8393629402972188521, 7234316402796163685,
       7310020887052516393, 8234033095304508515, 8747480847880449906,
       8245935277851950888, 7946993459895689852, 2987136102587065716,
       5003628290300136572, 4550972620349076082, 8245929724275009594,
       5649040559058156665, 2982630303883228271, 5655440803543282245,
       7881644865807335208, 4700138604099239013, 8245937412991248708,
       7882825952907590777, 4983559973837762149, 2904676802132669042,
       8537790503220427327, 4983645783105892965, 2904958277109379698,
       7236785694166039103, 7310028725417373289, 7014196369442496867,
       7886502681155038834, 8234108918506419049, 7165071409766625138,
       8460978848760

In [40]:
ide=np.identity(2)

In [41]:
ide

array([[1., 0.],
       [0., 1.]])

# Funtion Reshape()

In [43]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [44]:
rng.reshape(8,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87]])

In [45]:
rng=rng.reshape(8,11)

In [47]:
rng.shape

(8, 11)

In [49]:
rng=rng.ravel()

In [50]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [51]:
rng.shape

(88,)

In [52]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [53]:
arr=np.array(x)

In [54]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr.sum(axis =0)

array([12, 15, 18])

In [57]:
arr.sum(axis =1)

array([ 6, 15, 24])

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
arr.flat

In [63]:
for i in arr.flat:
    print (i)

1
2
3
4
5
6
7
8
9


In [64]:
arr.ndim

2

In [65]:
arr.size

9

In [66]:
arr.nbytes

72

In [67]:
one=np.array([1,2,43,25])

In [69]:
one.argmin()

np.int64(0)

In [70]:
one.argmax()

np.int64(2)

In [71]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr.argmin()

np.int64(0)

In [75]:
arr.argmax()

np.int64(8)

In [76]:
arr.argmax(axis=0)

array([2, 2, 2])

In [77]:
arr.argmax(axis=1)

array([2, 2, 2])

In [78]:
arr2=np.array([[12,43,23],
               [34,64,23],
               [23,90,10]]
               )

In [79]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr2


array([[12, 43, 23],
       [34, 64, 23],
       [23, 90, 10]])

In [81]:
arr+arr2

array([[13, 45, 26],
       [38, 69, 29],
       [30, 98, 19]])

In [82]:
arr*arr2

array([[ 12,  86,  69],
       [136, 320, 138],
       [161, 720,  90]])

In [83]:
import sys

In [84]:
py_ar=[1,2,3,4,5]

In [85]:
nyarr=np.array(py_ar)

In [86]:
nyarr

array([1, 2, 3, 4, 5])

In [87]:
sys.getsizeof(1)*len(py_ar)

140

In [88]:
nyarr.itemsize*nyarr.size

40